### ISSUE TITLE
Feature Request: menu item that shows all tags

### ISSUE THREAD

**Issue by PixedBo** [getk2/k2#461] opened 2018-11-02 15:23 UTC
It would be great to have a menu item that shows all tags (maybe sortable alphabetically or by number of articles). This woud also be great for SEO purpose as now when i click on an tag from an article view I get a weird URL, If I want good URLs I need to manually creat a menu item for EACH of the tags (hard to do if have a lot of tags).
Is this doable?
Thank you!

**Comment by fevangelou** [comment] 2018-12-09 07:48
To tackle the multiple URLs issue (which is basically caused by how the Joomla URL router works), you can simply create a menu item pointing to all categories and giving it a generic alias, e.g. "content". Then your tags without a direct menu item assigned to them will be displayed as /content/tag/tagname.

As for the menu item you propose, it can simply be done now using the tag cloud feature in K2 Tools (module) and a component like M2C (module to component) to load the module in place of the component.

**Closed** 2019-06-05 11:30 UTC
