### ISSUE TITLE
Investigate: Crash on K2 category pages after Joomla 3.7.0 / 3.7.1 update	

### ISSUE THREAD

**Issue by kricore** [getk2/k2#394] opened 2017-05-24 11:06 UTC
Sauce here:
http://www.joomlaworks.net/forum/k2-en/47836-crash-on-k2-category-pages-after-joomla-3-7-0-3-7-1-update
and here:
http://github.com/joomla/joomla-cms/issues/16185

**Comment by fevangelou** [comment] 2017-05-24 15:05
Resolved in Joomla.

**Closed by fevangelou** 2017-05-24 15:05 UTC

**Comment by Spudley** [comment] 2017-05-24 18:56
It's not resolved until it's merged. They're still discussing whether to accept it or not. 😐

**Comment by Spudley** [comment] 2017-07-12 14:02
@fevangelou  Hi. I think this ticket should be re-opened. Joomla don't seem to be interested in accepting the PR at their end, so the issue is not resolved in Joomla.
