### ISSUE TITLE
Database error saving new k2 item

### ISSUE THREAD

**Issue by posmishka** [getk2/k2#299] opened 2016-03-29 19:15 UTC
Subj.
We have an database error in admin panel in process of adding new k2 item, on "Save" or "Save & new" action. After the upgrading to k2 2.7
Detailed listing below:

> An error has occurred. 42000
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')}' at line 1 

enviroment:

```
PHP Built On    Linux ***********.pl 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64
Database Version    5.5.48
Database Collation  utf8_general_ci
Database Connection Collation   utf8mb4_general_ci
PHP Version     5.6.19
Web Server  Apache/2.2.15 (CentOS)
WebServer to PHP Interface  apache2handler
Joomla! Version     Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
```

**Founded TEMPORARY working solution is** 
to change joomla Database Type from PDO to MySQLi

**Comment by kavadas** [comment] 2016-03-30 09:41
Hi,

I don't think this has to do with K2. I think it has to do with Joomla! 3.5 . Do you get the same error when trying to save other kind of content ?

**Comment by posmishka** [comment] 2016-03-30 10:14
Hi, 
no, only adding new k2 item.
Joomla standard article adds with no errors.

also,
in warnings we have:
`PHP Notice:  Trying to get property of non-object in /home/wschodnik/web/wschodnik.pl/public_html/components/com_k2/views/itemlist/view.html.php on line 283`

and adding new k2 item we have nonblank (various from previous items) image in images tab.

**Comment by fevangelou** [comment] 2016-04-09 05:09
So by using MySQLi you don't get this SQL error you describe. Is that correct?

**Comment by posmishka** [comment] 2016-04-10 19:29
Hi,
>2 fevangelou, yes thats right.
just tested it once more.
there is no errors in MySQLi mode. Only in PDO
screen added
![error- 42000 2016-04-10 22-24-39](https://cloud.githubusercontent.com/assets/18150492/14412449/ae4a4eb6-ff6b-11e5-89af-4eeddc2a67e0.png)

**Comment by xstelios** [comment] 2016-05-06 09:35
I'm getting the same error in my error_log file `PHP Notice: Trying to get property of non-object in /public_html/components/com_k2/views/itemlist/view.html.php on line 283` I'm using php v.7.2, k2 v2.7 and MySQLi mode.

I also don't have any problems with saving new k2 items

Any idea?

**Comment by kavadas** [comment] 2016-05-06 16:10
@xstelios 

The notice should have been fixed with https://github.com/getk2/k2/commit/01b3a3623fb6c98b3ab01628aadee1b53cc21471 . 

The SQL issue is a different case. Probably it's caused by the MySQL driver.

**Closed** 2019-06-05 11:29 UTC
